### ISSUE TITLE
ruby 1.8.6 and no thin installed gives a LoadError

### ISSUE THREAD

**Issue by nevans** [quirkey/vegas#1]
and vegas seems to be checking for a NameError.

To reproduce, you can use rvm to install 1.8.6, and see my gist at http://gist.github.com/327059

**Comment by nevans** [comment]
oops.  I noticed that my "app" wasn't responding to your servers hook.  I've remedied that in the gist.  the bug still persists.

**Comment by quirkey** [comment]
Hey nevans

Thanks for pointing this out. I just pulled in your latest and pushed a new minor release.

--AQ

**Comment by nevans** [comment]
Marvelous.  Thanks!
