### ISSUE TITLE
kill command: custom --pid-file option ignored if --kill placed before

### ISSUE THREAD

**Issue by gentooboontoo** [quirkey/vegas#2]
"app --pid-file /tmp/app.pid --kill" works but not "app --kill --pid-file /tmp/app.pid" (pid file not found, vegas look for the default one).

That's because kill is called when parsing options and before custom pid-file been set.

a solution could be a "kill" flag and then call kill after all options have been parsed.

**Comment by quirkey** [comment]
Kill after all options have been parsed. Closed by 79b2bf59558189ef46efa20dd4875decbe74d8d7
